name: nasim
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.2.2
    - cloudpickle==3.1.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - filelock==3.18.0
    - fonttools==4.57.0
    - fsspec==2025.3.2
    - grpcio==1.71.0
    - gymnasium==1.1.1
    - jinja2==3.1.6
    - kiwisolver==1.4.8
    - markdown==3.8
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==2.2.5
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - packaging==25.0
    - pillow==11.2.1
    - prettytable==3.16.0
    - protobuf==6.30.2
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.2
    - setuptools==78.1.1
    - six==1.17.0
    - sympy==1.14.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - torch==2.7.0
    - triton==3.3.0
    - typing-extensions==4.13.2
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - wheel==0.45.1
